#%RAML 1.0
version: v1
title: Mule4 Worker Info

/workerinfo:
  get:
    responses:
      200:
        body:
          application/json:
            type: |
              {
                "title": "Mule4 Worker Info Response",
                "type": "object",
                "properties": {
                  "message": {
                    "type": "string"
                  }
                }
              }
            example: |
              {
                "version": "1.0.0",
                "origin": {
                    "app": {
                        "encoding": "UTF-8",
                        "name": "mule4-workerinfo-dev",
                        "standalone": true,
                        "workDir": "/opt/mule/./.mule/mule4-workerinfo-dev"
                    },
                    "server": {
                        "env": {
                            "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                            "ORG_ID": "8cc90329 ... 5db10edc3257",
                            "WORKERINFO_DEV_SERVICE_PORT": "8081",
                            "WRAPPER_JAVA_VERSION_MINOR": "0",
                            "METRICS_ACCELERATOR_PORT_8082_TCP_ADDR": "10.100.26.237",
                            "WORKERINFO_DEV_PORT_8082_TCP_PROTO": "tcp",
                            "APP_NAME": "mule4-workerinfo-dev",
                            "WRAPPER_BITS": "64",
                            "WRAPPER_BASE_NAME": "wrapper",
                            "WRAPPER_VERSION": "3.5.45",
                            "METRICS_ACCELERATOR_PORT_5701_TCP_ADDR": "10.100.26.237",
                            "METRICS_ACCELERATOR_SERVICE_HOST": "10.100.26.237",
                            "INFLUX_PUBLISH_HEAP_METRICS_DISABLED": "true",
                            "WRAPPER_HOST_NAME": "mule4-workerinfo-dev-5b5d56654c-mvdhp",
                            "WORKERINFO_DEV_SERVICE_PORT_HTTPS": "8082",
                            "MONITORING_PROXY": "",
                            "MULE_APP_NAME": "mule4-workerinfo-dev",
                            "PWD": "/opt/mule/lib/boot/exec",
                            "METRICS_ACCELERATOR_PORT_5701_TCP": "tcp://10.100.26.237:5701",
                            "JAVA_CA_CERTS": "/java/cacerts",
                            "WORKERINFO_DEV_PORT_5701_TCP": "tcp://10.100.215.127:5701",
                            "MULE_APP_LONG": "mule4-workerinfo-dev",
                            "METRICS_ACCELERATOR_PORT": "tcp://10.100.26.237:8081",
                            "METRICS_ACCELERATOR_SERVICE_PORT_HTTP": "8081",
                            "METRICS_ACCELERATOR_SERVICE_PORT_HAZELCAST": "5701",
                            "NODE_NAME": "172.31.2.209",
                            "JAVA_DEBIAN_VERSION": "8u265-b01-0ubuntu2~18.04",
                            "LC_ALL": "C.UTF-8",
                            "WRAPPER_JAVA_VERSION_REVISION": "265",
                            "MULE_APP": "mule4-workerinfo-dev",
                            "WRAPPER_JAVA_VERSION": "1.8.0_265",
                            "KUBERNETES_SERVICE_PORT_HTTPS": "443",
                            "SHLVL": "0",
                            "WRAPPER_OS": "linux",
                            "KUBERNETES_PORT": "tcp://10.100.0.1:443",
                            "METRICS_ACCELERATOR_PORT_5701_TCP_PROTO": "tcp",
                            "HTTP_PROXY": "",
                            "WORKERINFO_DEV_PORT_5701_TCP_ADDR": "10.100.215.127",
                            "INFLUX_PASSWORD": "0J20KXSpfXUvXXK4YmscPAVVs6oiIEKG",
                            "WRAPPER_CONF_DIR": "/mnt/overlay/opt/mule/conf",
                            "RTF_ID": "54111d24-13f3-42a8-9be3-1deed5227103",
                            "WRAPPER_LANG": "en",
                            "JAVA_VERSION": "8u265",
                            "WRAPPER_FILE_SEPARATOR": "/",
                            "HTTP_PROXY_PASSWORD": "",
                            "WORKERINFO_DEV_PORT_8082_TCP": "tcp://10.100.215.127:8082",
                            "KUBERNETES_PORT_443_TCP_ADDR": "10.100.0.1",
                            "WORKERINFO_DEV_SERVICE_HOST": "10.100.215.127",
                            "WRAPPER_PATH_SEPARATOR": ":",
                            "KUBERNETES_PORT_443_TCP_PROTO": "tcp",
                            "WORKERINFO_DEV_PORT": "tcp://10.100.215.127:8081",
                            "HTTP_PROXY_PORT": "-1",
                            "WRAPPER_JAVA_VERSION_MAJOR": "8",
                            "WORKERINFO_DEV_PORT_8082_TCP_ADDR": "10.100.215.127",
                            "METRICS_ACCELERATOR_PORT_8081_TCP_PORT": "8081",
                            "METRICS_ACCELERATOR_PORT_8082_TCP": "tcp://10.100.26.237:8082",
                            "WRAPPER_RUN_MODE": "console",
                            "INFLUX_USERNAME": "telegraf",
                            "METRICS_ACCELERATOR_PORT_8081_TCP_PROTO": "tcp",
                            "WRAPPER_HOSTNAME": "mule4-workerinfo-dev-5b5d56654c-mvdhp",
                            "HTTP_PROXY_HOST": "",
                            "METRICS_ACCELERATOR_PORT_8082_TCP_PORT": "8082",
                            "MULE_LIB": "/opt/mule/lib",
                            "WORKERINFO_DEV_SERVICE_PORT_HTTP": "8081",
                            "WORKERINFO_DEV_SERVICE_PORT_HAZELCAST": "5701",
                            "USE_PROXY_PROPERTIES": "false",
                            "WRAPPER_JAVA_VENDOR": "OpenJDK",
                            "METRICS_ACCELERATOR_SERVICE_PORT_HTTPS": "8082",
                            "KUBERNETES_PORT_443_TCP": "tcp://10.100.0.1:443",
                            "NAMESPACE_NAME": "c02e8cc1-358c-43f9-9f05-3551dd0e0f75",
                            "WORKERINFO_DEV_PORT_5701_TCP_PROTO": "tcp",
                            "WORKERINFO_DEV_PORT_8081_TCP_PORT": "8081",
                            "WRAPPER_EDITION": "Standard",
                            "POD_NAME": "mule4-workerinfo-dev-5b5d56654c-mvdhp",
                            "METRICS_ACCELERATOR_PORT_5701_TCP_PORT": "5701",
                            "WRAPPER_PID": "1",
                            "WORKERINFO_DEV_PORT_8082_TCP_PORT": "8082",
                            "WRAPPER_WORKING_DIR": "/opt/mule/lib/boot/exec",
                            "HTTP_PROXY_USERNAME": "",
                            "BC_FIPS_VERSION": "1.0.2",
                            "MASTER_ORG_ID": "88c6a526-485a-4a02-ae50-3a370bf85213",
                            "KUBERNETES_SERVICE_HOST": "10.100.0.1",
                            "METRICS_ACCELERATOR_SERVICE_PORT": "8081",
                            "LANG": "C.UTF-8",
                            "WRAPPER_BIN_DIR": "/opt/mule/lib/boot/exec",
                            "METRICS_ACCELERATOR_PORT_8081_TCP_ADDR": "10.100.26.237",
                            "WORKERINFO_DEV_PORT_5701_TCP_PORT": "5701",
                            "HTTP_PROXY_ENABLED": "false",
                            "WRAPPER_INIT_DIR": "/opt/mule",
                            "MULE_BASE": "/opt/mule",
                            "WORKERINFO_DEV_PORT_8081_TCP_ADDR": "10.100.215.127",
                            "WORKERINFO_DEV_PORT_8081_TCP_PROTO": "tcp",
                            "MULE_LICENSE": "/license/muleLicenseKey.lic",
                            "JDK_JAVA_OPTIONS": "--add-opens java.base/sun.net.www.protocol.file=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED  --add-opens java.desktop/java.beans=ALL-UNNAMED",
                            "METRICS_ACCELERATOR_PORT_8081_TCP": "tcp://10.100.26.237:8081",
                            "KUBERNETES_SERVICE_PORT": "443",
                            "MULE_HOME": "/opt/mule",
                            "WORKERINFO_DEV_PORT_8081_TCP": "tcp://10.100.215.127:8081",
                            "HOSTNAME": "mule4-workerinfo-dev-5b5d56654c-mvdhp",
                            "WRAPPER_ARCH": "x86",
                            "METRICS_ACCELERATOR_PORT_8082_TCP_PROTO": "tcp",
                            "KUBERNETES_PORT_443_TCP_PORT": "443",
                            "HOME": "/usr/src/app",
                            "HTTP_NO_PROXY": "0.0.0.0/0,.local,0.0.0.0/0,.local,,0.0.0.0/0,.local",
                            "ENV_ID": "c02e8cc1-358c-43f9-9f05-3551dd0e0f75"
                        },
                        "fileSeparator": "/",
                        "host": "mule4-workerinfo-dev-5b5d56654c-mvdhp",
                        "ip": "10.244.20.34",
                        "locale": {
                            "unicodeLocaleKeys": [],
                            "country": "",
                            "ISO3Language": "eng",
                            "displayName": "English",
                            "language": "en",
                            "displayVariant": "",
                            "displayLanguage": "English",
                            "script": "",
                            "unicodeLocaleAttributes": [],
                            "displayCountry": "",
                            "variant": "",
                            "ISO3Country": "",
                            "extensionKeys": [],
                            "displayScript": ""
                        },
                        "javaVendor": "Private Build",
                        "javaVersion": "1.8.0_265",
                        "osArch": "amd64",
                        "osName": "Linux",
                        "osVersion": "4.18.0-80.11.2.el8_0.x86_64",
                        "systemProperties": {
                            "java.vendor": "Private Build",
                            "anypoint.platform.proxy_password": "[PROXY PASSWORD]",
                            "sun.java.launcher": "SUN_STANDARD",
                            "sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
                            "javax.net.ssl.trustStorePassword": "changeit",
                            "os.name": "Linux",
                            "sun.boot.class.path": "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes",
                            "org.glassfish.grizzly.nio.transport.TCPNIOTransport.max-receive-buffer-size": "1048576",
                            "java.vm.specification.vendor": "Oracle Corporation",
                            "java.runtime.version": "1.8.0_265-8u265-b01-0ubuntu2~18.04-b01",
                            "wrapper.native_library": "wrapper",
                            "anypoint.platform.proxy_host": "",
                            "-Oanypoint.platform.client_secret": "[CLIENT SECRET]",
                            "wrapper.key": "",
                            "https.port": "8081",
                            "raml.xml.expandInternalEntities": "false",
                            "user.name": "app",
                            "anypoint.platform.proxy_username": "[PROXY USERNAME]",
                            "-Omule.env": "dev",
                            "javax.net.ssl.trustStoreType": "JKS",
                            "wrapper.jvm.port.min": "31000",
                            "mvel2.disable.jit": "TRUE",
                            "user.language": "en",
                            "AsyncLoggerConfig.ExceptionHandler": "org.mule.runtime.module.launcher.api.log4j2.AsyncLoggerExceptionHandler",
                            "sun.boot.library.path": "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64",
                            "xpath.provider": "com.mulesoft.licm.DefaultXPathProvider",
                            "http.port": "8081",
                            "java.version": "1.8.0_265",
                            "java.locale.providers": "COMPAT,CLDR,SPI",
                            "user.timezone": "GMT",
                            "java.net.preferIPv4Stack": "TRUE",
                            "anypoint.platform.analytics_multiple_consumers_enabled": "true",
                            "sun.arch.data.model": "64",
                            "java.endorsed.dirs": "/opt/mule/lib/endorsed",
                            "amf.plugins.xml.expandExternalEntities": "false",
                            "sun.cpu.isalist": "",
                            "sun.jnu.encoding": "UTF-8",
                            "file.encoding.pkg": "sun.io",
                            "mule.env": "dev",
                            "file.separator": "/",
                            "mule.metadata.cache.expirationInterval.millis": "5000",
                            "java.specification.name": "Java Platform API Specification",
                            "java.class.version": "52.0",
                            "java.security.properties": "/java/java.fips.security",
                            "jetty.git.hash": "afcf563148970e98786327af5e07c261fda175d3",
                            "mule.agent.configuration.folder": "/opt/mule/conf",
                            "log4j.configurationFactory": "org.apache.logging.log4j.core.config.xml.XmlConfigurationFactory",
                            "java.home": "/usr/lib/jvm/java-8-openjdk-amd64/jre",
                            "wrapper.version": "3.5.45-st",
                            "java.vm.info": "mixed mode",
                            "os.version": "4.18.0-80.11.2.el8_0.x86_64",
                            "jdk.http.auth.tunneling.disabledSchemes": "",
                            "org.eclipse.jetty.LEVEL": "WARN",
                            "path.separator": ":",
                            "java.vm.version": "25.265-b01",
                            "wrapper.pid": "1",
                            "java.util.prefs.PreferencesFactory": "com.mulesoft.licm.pref.MulePreferencesFactory",
                            "wrapper.jvm.port.max": "31999",
                            "wrapper.lang.folder": "../lang",
                            "wrapper.java.pid": "51",
                            "mule.home": "/opt/mule",
                            "anypoint.platform.proxy_port": "-1",
                            "java.awt.printerjob": "sun.print.PSPrinterJob",
                            "java.security.policy": "/java/java.policy",
                            "sun.io.unicode.encoding": "UnicodeLittle",
                            "awt.toolkit": "sun.awt.X11.XToolkit",
                            "enhance.mule.deployment.service.startup.listeners": "true",
                            "org.glassfish.grizzly.nio.transport.TCPNIOTransport.max-send-buffer-size": "1048576",
                            "log4j2.disable.jmx": "true",
                            "amf.plugins.xml.expandInternalEntities": "false",
                            "user.home": "/usr/src/app",
                            "java.specification.vendor": "Oracle Corporation",
                            "java.library.path": "/opt/mule/lib/boot",
                            "java.vendor.url": "http://java.oracle.com/",
                            "java.vm.vendor": "Private Build",
                            "wrapper.jvmid": "1",
                            "java.runtime.name": "OpenJDK Runtime Environment",
                            "mule.encoding": "UTF-8",
                            "sun.java.command": "org.mule.runtime.module.reboot.MuleContainerBootstrap",
                            "wrapper.lang.domain": "wrapper",
                            "java.class.path": "/opt/mule/lib:/opt/mule/conf:/opt/mule/lib/boot/commons-cli-1.2.jar:/opt/mule/lib/boot/commons-codec-1.15.jar:/opt/mule/lib/boot/disruptor-3.3.7.jar:/opt/mule/lib/boot/jackson-annotations-2.11.3.jar:/opt/mule/lib/boot/jackson-core-2.11.3.jar:/opt/mule/lib/boot/jackson-databind-2.11.3.jar:/opt/mule/lib/boot/jcl-over-slf4j-1.7.30.jar:/opt/mule/lib/boot/jul-to-slf4j-1.7.30.jar:/opt/mule/lib/boot/licm-2.1.7.jar:/opt/mule/lib/boot/log4j-1.2-api-2.13.3.jar:/opt/mule/lib/boot/log4j-api-2.13.3.jar:/opt/mule/lib/boot/log4j-core-2.13.3.jar:/opt/mule/lib/boot/log4j-slf4j-impl-2.13.3.jar:/opt/mule/lib/boot/mule-module-boot-ee-4.3.0-20210304.jar:/opt/mule/lib/boot/oscore-2.2.6.jar:/opt/mule/lib/boot/propertyset-1.3.jar:/opt/mule/lib/boot/slf4j-api-1.7.30.jar:/opt/mule/lib/boot/slf4j-ext-1.7.30.jar:/opt/mule/lib/boot/truelicense-1.29.jar:/opt/mule/lib/boot/truexml-1.29.jar:/opt/mule/lib/boot/wrapper-3.5.45.jar",
                            "-Oanypoint.platform.client_id": "XXX",
                            "log4j2.loggerContextFactory": "org.mule.runtime.module.launcher.log4j2.MuleLog4jContextFactory",
                            "anypoint.platform.client_id": "XXX",
                            "java.vm.specification.name": "Java Virtual Machine Specification",
                            "java.vm.specification.version": "1.8",
                            "sun.cpu.endian": "little",
                            "sun.os.patch.level": "unknown",
                            "wrapper.cpu.timeout": "10",
                            "java.io.tmpdir": "/tmp",
                            "anypoint.platform.analytics_base_uri": "https://analytics-ingest.anypoint.mulesoft.com",
                            "java.vendor.url.bug": "http://bugreport.sun.com/bugreport/",
                            "mule.disableLogSeparation": "1",
                            "anypoint.platform.client_secret": "[CLIENT SECRET]",
                            "os.arch": "amd64",
                            "java.awt.graphicsenv": "sun.awt.X11GraphicsEnvironment",
                            "mule.base": "/opt/mule",
                            "java.ext.dirs": "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext",
                            "user.dir": "/opt/mule/lib/boot/exec",
                            "mule.metadata.cache.entryTtl.minutes": "10",
                            "line.separator": "\n",
                            "java.vm.name": "OpenJDK 64-Bit Server VM",
                            "org.quartz.scheduler.skipUpdateCheck": "true",
                            "file.encoding": "UTF-8",
                            "raml.xml.expandExternalEntities": "false",
                            "mule.forceConsoleLog": "1",
                            "java.specification.version": "1.8",
                            "javax.net.ssl.trustStore": "/java/cacerts",
                            "wrapper.port": "34000",
                            "wrapper.arch": "x86"
                        },
                        "timeZone": "GMT",
                        "tmpDir": "/tmp",
                        "userDir": "/opt/mule/lib/boot/exec",
                        "userHome": "/usr/src/app",
                        "userName": "app"
                    }
                 }
              }
